

services:
  openclaw-gateway:
    image: ${OPENCLAW_IMAGE:-openclaw:local}
    environment:
      HOME: /home/node
      TZ: Europe/Paris
      TERM: xterm-256color
      OPENCLAW_GATEWAY_TOKEN: ${OPENCLAW_GATEWAY_TOKEN}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      BRAVE_SEARCH_API_KEY: ${BRAVE_SEARCH_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      REPLICATE_API_TOKEN: ${REPLICATE_API_TOKEN}
      CLAUDE_CODE_OAUTH_TOKEN: ${CLAUDE_CODE_OAUTH_TOKEN}
      CLAUDE_AI_SESSION_KEY: ${CLAUDE_AI_SESSION_KEY}
      CLAUDE_WEB_SESSION_KEY: ${CLAUDE_WEB_SESSION_KEY}
      CLAUDE_WEB_COOKIE: ${CLAUDE_WEB_COOKIE}
      GMAIL_ADDRESS: ${GMAIL_ADDRESS}
      GMAIL_APP_PASSWORD: ${GMAIL_APP_PASSWORD}
      AC_CRETEIL_EMAIL: ${AC_CRETEIL_EMAIL}
      AC_CRETEIL_PASSWORD: ${AC_CRETEIL_PASSWORD}
      AC_CRETEIL_SMTP: ${AC_CRETEIL_SMTP}
      AC_CRETEIL_SMTP_PORT: ${AC_CRETEIL_SMTP_PORT}
      AC_CRETEIL_IMAP_LOGIN: ${AC_CRETEIL_IMAP_LOGIN}
      HOTMAIL_ADDRESS: ${HOTMAIL_ADDRESS}
      HOTMAIL_APP_PASSWORD: ${HOTMAIL_APP_PASSWORD}
      HOTMAIL_IMAP: ${HOTMAIL_IMAP}
      HOTMAIL_IMAP_PORT: ${HOTMAIL_IMAP_PORT}
      HOTMAIL_SMTP: ${HOTMAIL_SMTP}
      HOTMAIL_SMTP_PORT: ${HOTMAIL_SMTP_PORT}
      AZURE_CLIENT_ID: ${AZURE_CLIENT_ID}
      AZURE_CLIENT_SECRET: ${AZURE_CLIENT_SECRET}
      AZURE_TENANT_ID: ${AZURE_TENANT_ID}
    volumes:
      - ${OPENCLAW_CONFIG_DIR}:/home/node/.openclaw
      - ${OPENCLAW_WORKSPACE_DIR}:/home/node/.openclaw/workspace
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/local/bin/docker:ro
    group_add:
      - "988"
    ports:
      - "127.0.0.1:${OPENCLAW_GATEWAY_PORT:-18789}:18789"
      - "127.0.0.1:${OPENCLAW_BRIDGE_PORT:-18790}:18790"
    init: true
    restart: unless-stopped
    command:
      [
        "node",
        "dist/index.js",
        "gateway",
        "--bind",
        "${OPENCLAW_GATEWAY_BIND:-lan}",
        "--port",
        "${OPENCLAW_GATEWAY_PORT:-18789}",
      ]

  openclaw-cli:
    image: ${OPENCLAW_IMAGE:-openclaw:local}
    environment:
      HOME: /home/node
      TERM: xterm-256color
      BROWSER: echo
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      CLAUDE_AI_SESSION_KEY: ${CLAUDE_AI_SESSION_KEY}
      CLAUDE_CODE_OAUTH_TOKEN: ${CLAUDE_CODE_OAUTH_TOKEN}
      CLAUDE_WEB_SESSION_KEY: ${CLAUDE_WEB_SESSION_KEY}
      CLAUDE_WEB_COOKIE: ${CLAUDE_WEB_COOKIE}
    volumes:
      - ${OPENCLAW_CONFIG_DIR}:/home/node/.openclaw
      - ${OPENCLAW_WORKSPACE_DIR}:/home/node/.openclaw/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    stdin_open: true
    tty: true
    init: true
    entrypoint: ["node", "dist/index.js"]
